import { Header } from "./_components/Header";

export const metadata = {
  title: "playground",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
